### provar api
GET http://localhost:4000/v1/users

### endpoint para registrar usuarios
POST http://localhost:5000/v1/users
Content-Type: application/json

{
  "tipo_usuario": 1,  
  "nombre": "Juan",
  "apellido": "Perez",
  "direccion": "Calle 123",
  "telefono": "809-555-1234",
  "email": "juan.perez@example.com",
  "fecha_nacimiento": "1990-05-15T00:00:00.000Z",
  "usuario": "juanperez",
  "contrasena": "securepassword",
  "fecha_registro": "2023-07-07T00:00:00.000Z",
  "estado": 1
}


### para obtener todos los usuarios
GET http://localhost:5000/v1/users

### endpoint para loguear usuarios
POST http://localhost:5000/v1/auth/login
Content-Type: application/json

{
  "usuario": "juanperez",
  "contrasena": "securepassword"
}


### para crear una asistencia
POST http://localhost:5000/v1/attendances/
Content-Type: application/json

{
  "id_usuario": 1,
  "fecha": "2024-07-12",
  "hora_entrada": "2024-07-12 15:30:00",
  "hora_salida": "2024-07-12 16:30:00"
}

### obtener todas las asistencias
GET http://localhost:5000/v1/attendances/

### obtener todas las asistencias de un usuario
GET http://localhost:5000/v1/attendances/1


### para registrar membresias
POST http://localhost:5000/v1/memberships/
Content-Type: application/json

{
  "tipo_membresia": 1,
  "id_usuario": 1,
  "fecha_inicio": "2024-07-13T00:00:00.000Z",
  "proximo_pago": "2024-08-13T00:00:00.000Z",
  "estado": 1
}

### para ver la membresia de un usuario
GET http://localhost:5000/v1/memberships/1


